M48
; DRILL file {KiCad 7.0.1} date Sun Aug 11 10:53:14 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-11T10:53:14-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0787
%
G90
G05
T1
X4.8815Y-5.0854
X5.1091Y-5.0854
T2
X4.5285Y-5.1594
X4.6959Y-5.1594
T3
X6.002Y-4.7776
X6.2776Y-4.7776
T4
X4.8386Y-3.9055
X5.8622Y-3.9055
T0
M30
